### ISSUE TITLE
Improve sample user keyword list

### ISSUE THREAD

**Issue by simsicon** [transist/echidna-rails#26]
Currently just a simple array. Shall fetch words from dicts.

**Comment by 0x1b2c** [comment]
Should resume the progress from the old system, related data already extracted to `/home/echidna/echidna.transi.st/shared/data.json` on echidna1 server. Check https://github.com/transist/echidna-rails/pull/30 for how it be dumped.

**Comment by 0x1b2c** [comment]
Feel free to work on it, but please don't run spider after the dumped data imported to your dev environment, to prevent potential data inconsistent.
