### ISSUE TITLE
Should link release_path/config/application.yml.example rather than application.yml in deploy.rb

### ISSUE THREAD

**Issue by simsicon** [transist/echidna-rails#33]
https://github.com/transist/echidna-rails/blob/develop/config/deploy.rb#L44

application.yml is gitignored.

**Comment by 0x1b2c** [comment]
Please note the link source is under shared path. We ignore config file so
developers can have different config reflect their different development
environment.
在 2013-5-20 上午11:17，"simsicon" notifications@github.com写道：

**Comment by simsicon** [comment]
I got a misunderstanding.
