### ISSUE TITLE
Retry to fetch user when tweet worker can not find the person in mongo

### ISSUE THREAD

**Issue by simsicon** [transist/echidna-rails#46]
In TweetWorker,

``` ruby
    person = Person.where(
      target_source: tweet_attrs.delete('target_source'),
      target_id: tweet_attrs.delete('target_person_id')
    ).first
```

Might return a nil sometimes.

**Comment by 0x1b2c** [comment]
A potential reason for this is, some users without city/gender/birth_year can't be persisted to the system due to the validations. I'll commit a patch for UserDecorator later.
