### ISSUE TITLE
Tweet#target_id is always nil

### ISSUE THREAD

**Issue by flyerhzm** [transist/echidna-rails#53]

**Comment by 0x1b2c** [comment]
How do you found it? I tried on server:

``` ruby
irb(main):006:0> Person.where(:target_id => nil).count
=> 0
```

**Comment by flyerhzm** [comment]
@rainux sorry, it's my typo, should be Tweet#target_id

**Comment by 0x1b2c** [comment]
Fixed with https://github.com/transist/echidna-rails/pull/54, also deployed and reset spider progress again.
