### ISSUE TITLE
Misunderstanding issue of Group model

### ISSUE THREAD

**Issue by 0x1b2c** [transist/echidna-rails#7]
The Group model was originally created to reflect a set of query conditions a user chose, since this project was only an alternative UI app. So Group and City have a 1-N relation. However for the system to store User and Group information, the Group and City should have a N-1 relation, like what we have in echidna-streaming.

I think we'd better use another model like Panel or Query for store UI query conditions, and change Group to work as the Group in echidna-streaming. Is it make sense? @flyerhzm

**Comment by flyerhzm** [comment]
oh, it's my bad, we should still use Group - City N - 1 relation, I will fix it.

**Comment by flyerhzm** [comment]
I have updated the code, group belongs_to city

**Comment by flyerhzm** [comment]
okay, group for backend, panel for UI query, #11
