### ISSUE TITLE
Get rid of "no space for /var" permanently

### ISSUE THREAD

**Issue by 0x1b2c** [transist/echidna-rails#73]
- Borrow space from /home to /var, since we're using lvm, it's possible to do it safely.
- Ensure all logs are rotated.
- Sweep out apt caches at fixed period.

**Comment by flyerhzm** [comment]
no space for /var again, prevent from updating cron jobs

**Comment by 0x1b2c** [comment]
I've increased /var to 43GB. Will keep watching the effect of logrotate config.
