### ISSUE TITLE
A problem of the way we calculate z-scores

### ISSUE THREAD

**Issue by 0x1b2c** [transist/echidna-rails#75]
The way we calculate z-scores have an assumption that all interested keywords are in current_stats, but this may not true, especially when calculating z-scores close to the beginning of current hour (for 1 day trends) or beginning of today (for 1 week/month trends).

That means if you watch the trends at morning or at the start of an hour, you may get much different results than at night or the end of an hour.

**Comment by flyerhzm** [comment]
yes, it's a problem, sounds like we can calculate the z-scores based on history_stats + last_stats (last hour or last day), it leads to trends change slower, but more meaningful and easier to cache result, @ballantyne what do you think?

**Comment by flyerhzm** [comment]
fixed in trends-recalc branch
