### ISSUE TITLE
Issue related to how we use the group with gender "both"

### ISSUE THREAD

**Issue by 0x1b2c** [transist/echidna-rails#76]
Currently group with gender "both" contain all kinds of people: female, male, and unknown. This rule also apply to Panel, check https://github.com/transist/echidna-rails/blob/develop/app/models/group.rb#L21 and https://github.com/transist/echidna-rails/blob/develop/app/models/group.rb#L30 for details.

This rule eventually cause a problem of frequent count calculation: A word from a person which gender is known (e.g. male or female) will be counted twice, the related tweets also shows duplicately. I have a commit that tries to avoid the duplicate tweets https://github.com/transist/echidna-rails/commit/f0e35ca718b949fd6ed4f578f5549f62c26e5476, finally I realized the root cause is the way we use "both" gender.

How should we resolve this issue?

**Comment by flyerhzm** [comment]
let's talk this next monday.
