### ISSUE TITLE
Echidna to Trends

### ISSUE THREAD

**Issue by flyerhzm** [transist/echidna-rails#78]

**Comment by simsicon** [comment]
So I deployed the app https://github.com/transist/echidna-qq, which will be used for applying QQ advanced account to echidna.transi.st, I DID change server_name, socket, restart,  and everything I can think about, but requesting to both echidna.transi.st and trends.transi.st are responded from echidna-qq. Do you guys have any ideas?

**Comment by flyerhzm** [comment]
How do you redirect trends to echidna at first?

**Comment by simsicon** [comment]
Add trends.transi.st to server_name of the echidna.transi.st config.
Then removed echidna.transi.st, added it to echidna-qq.transi.st config.

**Comment by flyerhzm** [comment]
there must be somewhere else you redirect trends to echidna, I have removed echidna_rails from nginx conf, but still can access trends.transi.st

**Comment by simsicon** [comment]
No, I only touched those two files, oh, I also removed lines related to echidna-ui in /home/echidna/nginx/conf/nginx.conf, but did not add anything new into it.

**Comment by flyerhzm** [comment]
how did you add the trends secondary domain?

**Comment by simsicon** [comment]
So it's fixed by modifying nginx conf on another server which port forwarding to the echidna1 server. Still got some issues I need to ask rainux, it's ok now.

**Comment by 0x1b2c** [comment]
Also please use `systemctl restart nginx.service` to restart nginx after
you change the config, if you didn't do it this way. Cause I found each
time you restarted nginx, it can't be control again with systemctl.

**Comment by simsicon** [comment]
Yes I did restart with the systemctl cmd.
